config/routes.rb
Typify::Application.routes.draw do
  root 'static_pages#home'   # Will change to StaticPages#home

  match '/random', to: 'person#random', via: 'get'
  match '/all',    to: 'person#index' , via: 'get'

  get "static_pages/home"
  get "person/new"
  get "person/show"
  get "person/index"

end

app/models/person.rb
class Person < ActiveRecord::Base

  def increment_views
    self.increment!(:num_views, 1)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/person_controller.rb
class PersonController < ApplicationController
  def new
  end

  def show
  end

  def index
  end

  def random
    selected_person = Person.first(:order => 'RANDOM()')
    selected_person.increment_views  # updates .views count on this Person's record

    redirect_to selected_person
    #for now
    flash[:notice] = "Approval Period Updated"
  end

  #def rate  #?  => handles button click?
    # updates Person.find(params[:id]) .rating
    # updates Person.find(params[:id]) .i_/e_/n_/s_/..._rating
  #end

  #def skip #?  => handles button 'Skip' click?
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/person_helper.rb
module PersonHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Typify</title>
  <%= stylesheet_link_tag    "application", media: "all",
                            "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5/js"></script>
  <![endif]-->
</head>
<body>
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
      <div class="container">
        <%= link_to "sample app", '#', id: "logo" %>
        <nav>
          <ul class="nav pull-right">
            <li><%= link_to "Home",        'StaticPages#home' %></li>
            <li><%= link_to "All People",  'Person#index' %></li>
            <li><%= link_to "New Person",  'Person#new' %></li>
            <li><%= link_to "Sign In",     '#' %></li>
          </ul>
        </nav>
      </div>
    </div>
  </header>
  <div class="container">
      <%= yield %>
  </div>
</body>
</html>

app/views/person/index.html.erb
<h1>Person#index</h1>
<p>Find me in app/views/person/index.html.erb</p>

app/views/person/new.html.erb
<h1>Person#new</h1>
<p>Find me in app/views/person/new.html.erb</p>

app/views/person/show.html.erb
<h1>Person#show</h1>
<p>Find me in app/views/person/show.html.erb</p>

app/views/static_pages/home.html.erb
<!-- > Homepage: StaticPages#home.html.erb -->

<div class="center hero-unit">
  <h1>Welcome to Typify!</h1>

  <h2>
    This is the home page for the
    Typify sample application.
  </h2>

  <row>
    <button><%= link_to "Rate People!", random_path %></button>
  </row>


  <%= link_to "Sign up now!", '#', class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>